name: S3 Downloader

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - name: Install Fyne
        run: go get fyne.io/fyne/v2

      - name: Build
        run: go build -ldflags="-w -s" -o s3-downloader cmd/main.go

      - name: Test
        run: go test -v ./...

      - name: Package for Linux
        run: fyne package -os linux -icon icon.png

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: s3-downloader-linux
          path: s3-downloader.tar.xz

      - name: Package for Windows
        run: fyne package -os windows -icon icon.png

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: s3-downloader-windows
          path: s3-downloader.exe
