name: Go CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

permissions: write-all

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.24"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -v

      - name: Lint code
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.59.1
          args: --timeout 5m

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: |
          gosec ./...
        continue-on-error: true # Continue the workflow even if gosec fails

      - name: Archive gosec report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: gosec-report
          path: gosec_report.json

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            **/test-results.xml

      - name: Archive lint results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: lint-results
          path: |
            **/lint-results.json
